### PR TITLE
Implement Authentication based on JWT

### PR DESCRIPTION
**Pull request by indocomsoft**

### CODE REVIEW

**Review by sciffany — APPROVED** [review]
Nice

**Review by sciffany — APPROVED** [review]
Alright. Good job adding JWT gem.

**Review by sciffany — APPROVED** [review]

**Review by sciffany — APPROVED** [review]
Good job adding authentication methods in controller

**Review by sciffany — APPROVED** [review]
Wow, rubocop is strict. Good job.

**Comment by indocomsoft** [comment]
Eh, this is still a WIP, you shouldn't approve yet haha @sciffany

**Comment by indocomsoft** [comment]
@sciffany alright you can review now

**Pull request merged**
